In [28]:
__author__ = 'giulio'

import sys
import os
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import utils
%matplotlib inline

pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

folders = os.listdir("drivers/")
drivers = filter(lambda idd: idd[0] != ".", folders)

In [29]:
reload(utils)

<module 'utils' from 'utils.pyc'>

In [30]:
drivers = ["2", "3", "1000", "1001", "1002", "1003"]
import os
folders = os.listdir("drivers/")
#drivers = filter(lambda idd: idd[0] != "." and int(idd)<40, folders)
%time feats = utils.extract_features_drivers(drivers)
new_shape = (feats.shape[0]*feats.shape[1], feats.shape[2])
feats = feats.reshape(new_shape)
#print feats[0]



CPU times: user 28 ms, sys: 16 ms, total: 44 ms
Wall time: 5.37 s
2
1001
1000
3
1002
1003


In [15]:
ind = 14
print feats[:, ind].min()
print feats[:, ind].max()
#print feats[:, ind].mean()

np.histogram(feats[:, 31], bins=np.linspace(-5.0, 5.0, 11))


0.00238663484487
1.0


(array([   0,    0,    0,    0,    0, 1400,    0,    0,    0,    0]),
 array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]))

In [30]:
np.pi*2

6.283185307179586

In [40]:
dr = "subm_508e477562ad"

a = pd.read_csv("subm_508e477562ad/10.csv").as_matrix()[:, 1]
b = pd.read_csv("subm_508e477562ad/1001.csv").as_matrix()[:, 1]
c = pd.read_csv("subm_508e477562ad/1002.csv").as_matrix()[:, 1]
d = pd.read_csv("subm_508e477562ad/1003.csv").as_matrix()[:, 1]

In [42]:
print np.histogram(a)
print np.histogram(b)
print np.histogram(c)
print np.histogram(d)

(array([10, 10,  9,  7, 13,  8, 10, 16, 27, 89]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))
(array([ 6, 17,  5,  8,  9,  7, 12, 23, 27, 85]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))
(array([ 3, 13, 12,  9, 12, 14, 12, 11, 23, 90]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))
(array([ 17,  12,  10,   2,   2,   7,   9,  15,  21, 104]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))


(array([ 2, 13, 14, 12,  7, 16, 17, 14, 26, 78]),
 array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ]))